# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Numero')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoye'), ('approved', 'Approuve'), ('rejected', 'Refuse'), ('expired', 'Expire')], default='draft', max_length=20, verbose_name='Statut')),
                ('global_margin_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Si renseignee, remplace la marge de chaque ligne.', max_digits=6, null=True, verbose_name='Marge globale (%)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='Taux TVA (%)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes internes')),
                ('notes_client', models.TextField(blank=True, default='', verbose_name='Notes pour le client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoye le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_snapshot', models.CharField(max_length=200, verbose_name='Service')),
                ('service_code_snapshot', models.CharField(max_length=30, verbose_name='Code')),
                ('service_unit_snapshot', models.CharField(max_length=20, verbose_name='Unite')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantite')),
                ('labor_cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Cout M.O. / unite')),
                ('margin_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Marge (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['budget', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Produit (snapshot)')),
                ('unit_snapshot', models.CharField(max_length=20, verbose_name='Unite (snapshot)')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantite')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, help_text="Prix gele au moment de l'emission du devis.", max_digits=14, verbose_name='Prix unitaire HT (snapshot)')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='budget.budgetitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_usages', to='catalog.product', verbose_name='Produit')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_material_usages', to='suppliers.supplier', verbose_name='Fournisseur choisi')),
            ],
            options={
                'verbose_name': 'Materiau de la ligne',
                'verbose_name_plural': 'Materiaux de la ligne',
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status', '-created_at'], name='budget_budg_status_47d690_idx'),
        ),
    ]
