# Generated by Django 5.2.13 on 2026-04-26 00:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0002_legal_form_fk'),
        ('projects', '0001_initial'),
        ('services', '0002_service_sale_price_per_unit_service_time_per_unit'),
        ('suppliers', '0002_legal_form_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['budget', 'chapter', 'order'], 'verbose_name': 'Linha de orçamento', 'verbose_name_plural': 'Linhas de orçamento'},
        ),
        migrations.AlterModelOptions(
            name='budgetitemmaterial',
            options={'verbose_name': 'Material da linha', 'verbose_name_plural': 'Materiais da linha'},
        ),
        migrations.AddField(
            model_name='budget',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
        migrations.AddField(
            model_name='budget',
            name='payment_terms',
            field=models.TextField(blank=True, default='', help_text='Ex: 30% na assinatura, 40% no início, 30% na entrega.', verbose_name='Condições de pagamento'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição (override)'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='unit_price_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Se preenchido, substitui o preço calculado pelo catálogo.', max_digits=14, null=True, verbose_name='Preço unit. (override)'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=6, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Desconto global (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='global_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchida, substitui a margem de cada linha.', max_digits=6, null=True, verbose_name='Margem global (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes_client',
            field=models.TextField(blank=True, default='', verbose_name='Notas para o cliente'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.project', verbose_name='Obra / Projecto'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('expired', 'Expirado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válido até'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Usado como padrão para novos itens. Cada item pode ter IVA próprio.', max_digits=6, verbose_name='IVA padrão (%)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='labor_cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Custo M.O. / unidade'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Margem (%)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service_code_snapshot',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service_name_snapshot',
            field=models.CharField(max_length=200, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service_unit_snapshot',
            field=models.CharField(max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_usages', to='catalog.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='product_name_snapshot',
            field=models.CharField(max_length=255, verbose_name='Produto (snapshot)'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_material_usages', to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=4, help_text='Preço congelado no momento da emissão do orçamento.', max_digits=14, verbose_name='Preço unit. HT (snapshot)'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='unit_snapshot',
            field=models.CharField(max_length=20, verbose_name='Unidade (snapshot)'),
        ),
        migrations.CreateModel(
            name='BudgetChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='budget.budget', verbose_name='Orçamento')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.budgetchapter', verbose_name='Capítulo pai')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['budget', 'order'],
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='budget.budgetchapter', verbose_name='Capítulo'),
        ),
    ]
