# Generated by Django 5.2.13 on 2026-04-29 17:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_options_alter_budgetitem_options_and_more'),
        ('catalog', '0002_alter_product_options_alter_productcategory_options_and_more'),
        ('clients', '0002_legal_form_fk'),
        ('projects', '0002_projectinteraction_projectlabourentry_and_more'),
        ('services', '0002_service_sale_price_per_unit_service_time_per_unit'),
        ('suppliers', '0003_alter_supplier_options_alter_supplieraddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='budgetchapter',
            options={'ordering': ['budget', 'order'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['budget', 'chapter', 'order'], 'verbose_name': 'Budget line', 'verbose_name_plural': 'Budget lines'},
        ),
        migrations.AlterModelOptions(
            name='budgetitemmaterial',
            options={'verbose_name': 'Line material', 'verbose_name_plural': 'Line materials'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Global discount (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='global_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="If set, overrides each line's margin.", max_digits=6, null=True, verbose_name='Global margin (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes_client',
            field=models.TextField(blank=True, default='', verbose_name='Notes for client'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='payment_terms',
            field=models.TextField(blank=True, default='', help_text='E.g. 30% on signature, 40% at start, 30% on delivery.', verbose_name='Payment terms'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.project', verbose_name='Project / site'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Default for new items. Each item may have its own VAT rate.', max_digits=6, verbose_name='Default VAT (%)'),
        ),
        migrations.AlterField(
            model_name='budgetchapter',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='budget.budget', verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='budgetchapter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='budgetchapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.budgetchapter', verbose_name='Parent chapter'),
        ),
        migrations.AlterField(
            model_name='budgetchapter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='budget.budgetchapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description (override)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='labor_cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Labor cost / unit'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Margin (%)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service_code_snapshot',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service_name_snapshot',
            field=models.CharField(max_length=200, verbose_name='Service (snapshot)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='service_unit_snapshot',
            field=models.CharField(max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='unit_price_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='If set, replaces the catalog-calculated unit price.', max_digits=14, null=True, verbose_name='Unit price (override)'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=6, verbose_name='VAT (%)'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_usages', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='product_name_snapshot',
            field=models.CharField(max_length=255, verbose_name='Product (snapshot)'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_material_usages', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=4, help_text='Price frozen when the budget was issued.', max_digits=14, verbose_name='Unit price excl. VAT (snapshot)'),
        ),
        migrations.AlterField(
            model_name='budgetitemmaterial',
            name='unit_snapshot',
            field=models.CharField(max_length=20, verbose_name='Unit (snapshot)'),
        ),
    ]
