# Generated by Django 5.2.13 on 2026-05-08 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_deleted_at_budget_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Locked'),
        ),
        migrations.AddField(
            model_name='budget',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked at'),
        ),
        migrations.AddField(
            model_name='budget',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_locked', to=settings.AUTH_USER_MODEL, verbose_name='Locked by'),
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version')),
                ('locked_at', models.DateTimeField(verbose_name='Locked at')),
                ('reason', models.CharField(blank=True, default='', help_text='approved, manual, etc.', max_length=80, verbose_name='Reason')),
                ('snapshot', models.JSONField(verbose_name='Snapshot')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='budget.budget', verbose_name='Budget')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Locked by')),
            ],
            options={
                'verbose_name': 'Budget version',
                'verbose_name_plural': 'Budget versions',
                'ordering': ['-version_number'],
                'unique_together': {('budget', 'version_number')},
            },
        ),
    ]
