# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('trade_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom commercial')),
                ('category', models.CharField(choices=[('professional', 'Professionnel'), ('private', 'Prive')], default='professional', max_length=20, verbose_name='Categorie')),
                ('legal_form', models.CharField(blank=True, choices=[('srl', 'SRL'), ('sa', 'SA'), ('scs', 'SCS'), ('snc', 'SNC'), ('asbl', 'ASBL'), ('independant', 'Independant'), ('other', 'Autre')], default='', max_length=20, verbose_name='Forme juridique')),
                ('vat_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numero TVA')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Taux TVA (%)')),
                ('responsible', models.CharField(blank=True, default='', max_length=255, verbose_name='Responsable')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Informations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Libelle')),
                ('street', models.CharField(max_length=255, verbose_name='Rue')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, default='', max_length=255, verbose_name='Complement')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='Region')),
                ('country', models.CharField(default='Belgium', max_length=100, verbose_name='Pays')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par defaut')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('general', 'General'), ('financial', 'Finance'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('is_default', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
