# Generated by Django 5.2.13 on 2026-04-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_legal_form_fk'),
        ('workforce', '0009_add_planning_vehicle_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplieraddress',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('private', 'Private')], default='professional', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='legal_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='workforce.legalform', verbose_name='Legal form'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Account manager'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Trade name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='VAT rate (%)'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='country',
            field=models.CharField(default='Brazil', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Primary address'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='contact_type',
            field=models.CharField(choices=[('general', 'General'), ('financial', 'Financial'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Contact type'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Primary contact'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
