# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Work Registration Type',
                'verbose_name_plural': 'Work Registration Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('has_work_registration', models.BooleanField(default=False, verbose_name='Has work registration')),
                ('work_registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration number')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client', verbose_name='Client')),
                ('contacts', models.ManyToManyField(blank=True, related_name='projects', to='clients.clientcontact', verbose_name='Contacts')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Managers')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('work_registration_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workregistrationtype', verbose_name='Registration type')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client'], name='projects_pr_client__06571b_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx')],
            },
        ),
    ]
