# Generated by Django 5.2.13 on 2026-04-29 17:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_productcategory_options_and_more'),
        ('projects', '0001_initial'),
        ('suppliers', '0002_legal_form_fk'),
        ('timesheets', '0002_alter_timesheet_options'),
        ('workforce', '0009_add_planning_vehicle_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('interaction_type', models.CharField(choices=[('meeting', 'Meeting'), ('email', 'Email'), ('phone', 'Phone'), ('visit', 'Site visit'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(blank=True, default='', verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Interaction',
                'verbose_name_plural': 'Project Interactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLabourEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Hours')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Hourly rate (€)')),
                ('is_overtime', models.BooleanField(default=False, verbose_name='Overtime')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, verbose_name='Overtime multiplier')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_entries', to='projects.project', verbose_name='Project')),
                ('timesheet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_entry', to='timesheets.timesheet', verbose_name='Timesheet')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_labour_entries', to='workforce.collaborator', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Labour Entry',
                'verbose_name_plural': 'Labour Entries',
                'ordering': ['-date', 'worker__name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Unit price (€)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_materials', to='catalog.product', verbose_name='Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Material',
                'verbose_name_plural': 'Project Materials',
                'ordering': ['-date', 'description'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Invoice reference')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount_ht', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Amount excl. VAT (€)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT rate (%)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='projects.project', verbose_name='Project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_invoices', to='suppliers.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'ordering': ['-date'],
            },
        ),
    ]
