# Generated by Django 5.2.13 on 2026-04-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectinteraction_projectlabourentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.AddField(
            model_name='project',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='project',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complement'),
        ),
        migrations.AddField(
            model_name='project',
            name='address_country',
            field=models.CharField(blank=True, default='Bélgica', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='project',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='address_postcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='project',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Street'),
        ),
    ]
