# Generated by Django 5.2.13 on 2026-04-29 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_clientaddress_options_alter_client_category_and_more'),
        ('projects', '0002_projectinteraction_projectlabourentry_and_more'),
        ('suppliers', '0003_alter_supplier_options_alter_supplieraddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Amount (€)')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='projects.project', verbose_name='Project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='suppliers.supplier', verbose_name='Supplier')),
                ('supplier_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable', to='projects.projectsupplierinvoice', verbose_name='Supplier invoice')),
            ],
            options={
                'verbose_name': 'Payable',
                'verbose_name_plural': 'Payables',
                'ordering': ['due_date', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Payment date')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Amount (€)')),
                ('method', models.CharField(choices=[('transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='transfer', max_length=20, verbose_name='Method')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference / transaction ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.payable', verbose_name='Payable')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Amount (€)')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Receivable',
                'verbose_name_plural': 'Receivables',
                'ordering': ['due_date', '-amount'],
            },
        ),
    ]
