# Generated by Django 5.2.13 on 2026-04-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('projects', '0002_projectinteraction_projectlabourentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='invoicing.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.receivable', verbose_name='Receivable'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['status', 'due_date'], name='finance_pay_status_e67448_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['supplier'], name='finance_pay_supplie_ea1327_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['status', 'due_date'], name='finance_rec_status_aa82ac_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['client'], name='finance_rec_client__1b0839_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payable__isnull', False), ('receivable__isnull', True)), models.Q(('payable__isnull', True), ('receivable__isnull', False)), _connector='OR'), name='payment_has_exactly_one_parent'),
        ),
    ]
