# Generated by Django 5.2.13 on 2026-05-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('finance', '0002_initial'),
        ('invoicing', '0002_add_invoice_type_and_line_type'),
        ('subcontractors', '0003_alter_subcontractor_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='subcontractors.subcontractor', verbose_name='Subcontractor'),
        ),
        migrations.AddField(
            model_name='payable',
            name='subcontractor_invoice_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_entry', to='contracts.subcontractorinvoice', verbose_name='Subcontractor invoice'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='statement',
            field=models.OneToOneField(blank=True, limit_choices_to={'statement_type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable', to='contracts.statement', verbose_name='Statement (EA)'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='invoicing.invoice', verbose_name='Invoice'),
        ),
    ]
