# Generated by Django 5.2.13 on 2026-05-02 14:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_clientaddress_options_alter_client_category_and_more'),
        ('finance', '0002_initial'),
        ('projects', '0004_projectciawparticipant'),
        ('subcontractors', '0003_alter_subcontractor_category_and_more'),
        ('suppliers', '0003_alter_supplier_options_alter_supplieraddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('client', 'Client contract'), ('subcontractor', 'Subcontractor contract'), ('supplier', 'Supplier contract'), ('other', 'Other')], default='client', max_length=20, verbose_name='Type')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference / number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Signed date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Discount (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT rate (%)')),
                ('notes_internal', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('notes_client', models.TextField(blank=True, default='', verbose_name='Notes to counterpart')),
                ('template_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Template ref (future)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='projects.project', verbose_name='Project')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='subcontractors.subcontractor', verbose_name='Subcontractor')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='suppliers.supplier', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Addendum number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Signed date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20, verbose_name='Status')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Discount (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT rate (%)')),
                ('notes_internal', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('notes_sub', models.TextField(blank=True, default='', verbose_name='Notes to subcontractor')),
                ('template_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Template ref (future)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addenda_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='projects.project', verbose_name='Project')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='subcontractors.subcontractor', verbose_name='Subcontractor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addenda_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('contract', models.ForeignKey(limit_choices_to={'contract_type': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='contracts.contract', verbose_name='Client contract')),
            ],
            options={
                'verbose_name': 'Addendum',
                'verbose_name_plural': 'Addenda',
                'ordering': ['contract', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('line_type', models.CharField(choices=[('line', 'Line'), ('title', 'Title (H1)'), ('h2', 'Subtitle (H2)'), ('h3', 'Heading H3'), ('h4', 'Heading H4'), ('comment', 'Comment'), ('page_break', 'Page break')], default='line', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Unit price (€)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Discount (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT rate (%)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Line',
                'verbose_name_plural': 'Contract Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AddendumLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('line_type', models.CharField(choices=[('line', 'Line'), ('title', 'Title (H1)'), ('h2', 'Subtitle (H2)'), ('h3', 'Heading H3'), ('h4', 'Heading H4'), ('comment', 'Comment'), ('page_break', 'Page break')], default='line', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Unit price (€)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Discount (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT rate (%)')),
                ('addendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.addendum')),
                ('source_contract_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addendum_copies', to='contracts.contractline', verbose_name='Source contract line')),
            ],
            options={
                'verbose_name': 'Addendum Line',
                'verbose_name_plural': 'Addendum Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('client', 'EA to Client'), ('subcontractor', 'EA to Subcontractor')], max_length=20, verbose_name='Type')),
                ('number', models.CharField(max_length=20, verbose_name='EA number')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Period start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Period end')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Status')),
                ('notes_internal', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('notes_external', models.TextField(blank=True, default='', verbose_name='Notes to recipient')),
                ('template_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Template ref (future)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addendum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='contracts.addendum', verbose_name='Addendum')),
                ('contract', models.ForeignKey(blank=True, limit_choices_to={'contract_type': 'client'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='contracts.contract', verbose_name='Contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Amount (€)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.statement')),
            ],
            options={
                'verbose_name': 'Statement Line',
                'verbose_name_plural': 'Statement Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Invoice number')),
                ('invoice_date', models.DateField(verbose_name='Invoice date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount (€)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addendum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_invoices', to='contracts.addendum', verbose_name='Addendum')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_invoice', to='finance.payable', verbose_name='Payable')),
                ('statement', models.ForeignKey(blank=True, limit_choices_to={'statement_type': 'subcontractor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_invoices', to='contracts.statement', verbose_name='EA (statement)')),
            ],
            options={
                'verbose_name': 'Subcontractor Invoice',
                'verbose_name_plural': 'Subcontractor Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type', 'status'], name='contracts_c_contrac_fd43fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addendum',
            unique_together={('contract', 'number')},
        ),
    ]
