# Generated by Django 5.2.13 on 2026-05-02 19:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('suppliers', '0003_alter_supplier_options_alter_supplieraddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Signed date')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_contracts', to='suppliers.supplier', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_contracts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Supplier Contract',
                'verbose_name_plural': 'Supplier Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Product / Description')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Unit price (€)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.suppliercontract')),
            ],
            options={
                'verbose_name': 'Supplier Contract Line',
                'verbose_name_plural': 'Supplier Contract Lines',
                'ordering': ['order', 'id'],
            },
        ),
    ]
