# Generated by Django 5.2.13 on 2026-05-01 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0009_add_planning_vehicle_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('brand', models.CharField(blank=True, default='', max_length=80, verbose_name='Brand')),
                ('model', models.CharField(blank=True, default='', max_length=80, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Serial Number')),
                ('internal_code', models.CharField(blank=True, default='', help_text='Optional internal reference (e.g. EQ-001)', max_length=30, verbose_name='Internal Code')),
                ('status', models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned'), ('maintenance', 'In Maintenance'), ('sold', 'Sold'), ('written_off', 'Written Off')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10, verbose_name='Condition')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Purchase Price (€)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.equipmentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Loaned At')),
                ('expected_return', models.DateField(blank=True, null=True, verbose_name='Expected Return')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Returned At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('ticket_printed', models.BooleanField(default=False, verbose_name='Ticket Printed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_loans', to='workforce.collaborator', verbose_name='Collaborator')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='equipment.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Loan',
                'verbose_name_plural': 'Equipment Loans',
                'ordering': ['-loaned_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sale Date')),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Sale Price (€)')),
                ('installments', models.PositiveSmallIntegerField(default=1, verbose_name='Installments')),
                ('amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Amount Paid (€)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid Off')], default='pending', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_purchases', to='workforce.collaborator', verbose_name='Collaborator')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='equipment.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Sale',
                'verbose_name_plural': 'Equipment Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
