# Generated by Django 5.2.13 on 2026-05-02 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('document_type', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice'), ('contract', 'Client Contract'), ('addendum', 'Addendum'), ('statement', 'Progress Statement (EA)'), ('supplier_order', 'Supplier Purchase Order'), ('sub_order', 'Subcontractor Order'), ('credit_note', 'Credit Note'), ('other', 'Other')], max_length=30, verbose_name='Document type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('is_system', models.BooleanField(default=False, verbose_name='System template (non-editable)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default for this type')),
                ('section_page_header', models.TextField(blank=True, default='', verbose_name='Page header (repeated)')),
                ('section_page_footer', models.TextField(blank=True, default='', verbose_name='Page footer (repeated)')),
                ('section_header_generic', models.TextField(blank=True, default='', verbose_name='Generic header (logo + parties)')),
                ('section_header_document', models.TextField(blank=True, default='', verbose_name='Document header (intro text)')),
                ('section_lines_config', models.JSONField(blank=True, default=dict, verbose_name='Lines table config')),
                ('section_footer_document', models.TextField(blank=True, default='', verbose_name='Document footer (totals, conditions, signatures)')),
                ('custom_css', models.TextField(blank=True, default='', verbose_name='Custom CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['document_type', 'name'],
            },
        ),
    ]
