# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade Name')),
                ('category', models.CharField(choices=[('professional', 'Professionnel'), ('private', 'Privé')], default='professional', max_length=20, verbose_name='Category')),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='VAT Number')),
                ('legal_form', models.CharField(blank=True, choices=[('srl', 'SRL'), ('sa', 'SA'), ('scs', 'SCS'), ('snc', 'SNC'), ('asbl', 'ASBL'), ('independant', 'Indépendant'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Legal Form')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT Rate (%)')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsible')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('blocked', 'Blocked')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Subcontractor',
                'verbose_name_plural': 'Subcontractors',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vat_number', ''), _negated=True), fields=('vat_number',), name='unique_vat_number')],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Label')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(default='Belgium', max_length=100, verbose_name='Country')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Address')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='subcontractors.subcontractor', verbose_name='Subcontractor')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='SubcontractorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('general', 'Général'), ('financial', 'Finance'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Contact Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('is_default', models.BooleanField(default=False, verbose_name='Main Contact')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='subcontractors.subcontractor', verbose_name='Subcontractor')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
