# Generated by Django 5.2.13 on 2026-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractors', '0002_legal_form_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('private', 'Private')], default='professional', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcontractoraddress',
            name='country',
            field=models.CharField(default='Brazil', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='subcontractoraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Primary address'),
        ),
        migrations.AlterField(
            model_name='subcontractorcontact',
            name='contact_type',
            field=models.CharField(choices=[('general', 'General'), ('financial', 'Financial'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='subcontractorcontact',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Primary contact'),
        ),
    ]
