# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='services.servicecategory', verbose_name='Categorie parente')),
            ],
            options={
                'verbose_name': 'Categorie de service',
                'verbose_name_plural': 'Categories de services',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description technique')),
                ('labor_cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Cout M.O. / unite')),
                ('default_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Peut etre ajustee dans le devis.', max_digits=6, verbose_name='Marge par defaut (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(help_text='Unite dans laquelle le service est mesure. Ex: m2, m3, ml, un.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.unitofmeasure', verbose_name='Unite du service')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantite par unite de service')),
                ('waste_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Perte technique (%)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Observation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usages', to='catalog.product', verbose_name='Produit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Materiau du service',
                'verbose_name_plural': 'Materiaux du service',
                'unique_together': {('service', 'product')},
            },
        ),
    ]
