# Generated by Django 5.2.13 on 2026-04-25 22:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sale_price_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Preço cobrado ao cliente por unidade. 0 = usar preço sugerido.', max_digits=14, verbose_name='Preço de venda / unidade'),
        ),
        migrations.AddField(
            model_name='service',
            name='time_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tempo estimado em minutos para executar uma unidade do serviço.', max_digits=8, verbose_name='Tempo de execução / unidade (min)'),
        ),
    ]
