# Generated by Django 5.2.13 on 2026-04-29 17:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_productcategory_options_and_more'),
        ('services', '0002_service_sale_price_per_unit_service_time_per_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service category', 'verbose_name_plural': 'Service categories'},
        ),
        migrations.AlterModelOptions(
            name='servicematerial',
            options={'verbose_name': 'Service material', 'verbose_name_plural': 'Service materials'},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Can be adjusted in the quote.', max_digits=6, verbose_name='Default margin (%)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Technical description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='labor_cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Labor cost / unit'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sale_price_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price charged to the client per unit. 0 = use suggested price.', max_digits=14, verbose_name='Sale price / unit'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated minutes to execute one unit of the service.', max_digits=8, verbose_name='Execution time / unit (minutes)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(help_text='Unit in which the service is measured, e.g. m², m³, m, ea.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.unitofmeasure', verbose_name='Service unit of measure'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='services.servicecategory', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='servicematerial',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='servicematerial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usages', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='servicematerial',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantity per service unit'),
        ),
        migrations.AlterField(
            model_name='servicematerial',
            name='waste_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Waste / scrap (%)'),
        ),
    ]
