# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom commercial')),
                ('category', models.CharField(choices=[('private', 'Privé'), ('professional', 'Professionnel')], default='professional', max_length=20, verbose_name='Catégorie')),
                ('legal_form', models.CharField(blank=True, choices=[('srl', 'SRL'), ('sa', 'SA'), ('scs', 'SCS'), ('snc', 'SNC'), ('asbl', 'ASBL'), ('independant', 'Indépendant'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Forme juridique')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='TVA')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxe TVA (%)')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Informations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé')),
                ('street', models.CharField(max_length=255, verbose_name='Rue')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région')),
                ('country', models.CharField(default='Belgium', max_length=100, verbose_name='Pays')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('general', 'Général'), ('financial', 'Finance'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Type de contact')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('is_default', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
