# Generated by Django 5.2.13 on 2026-04-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_legal_form_fk'),
        ('workforce', '0009_add_planning_vehicle_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('private', 'Private'), ('professional', 'Professional')], default='professional', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='workforce.legalform', verbose_name='Legal form'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account manager'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT rate (%)'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='country',
            field=models.CharField(default='Brazil', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Primary address'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='contact_type',
            field=models.CharField(choices=[('general', 'General'), ('financial', 'Financial'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Contact type'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Primary contact'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
