# Generated by Django 5.2.13 on 2026-05-06 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessprofile',
            options={'ordering': ['group__name'], 'verbose_name': 'Access profile', 'verbose_name_plural': 'Access profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='accessprofile',
            name='color',
            field=models.CharField(choices=[('accent', 'Orange'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('gray', 'Gray')], default='gray', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='accessprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accessprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to='auth.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_users', to='auth.group', verbose_name='Access profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=100)),
                ('hidden_cols', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'table_id')},
            },
        ),
    ]
