"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Em produção com DEBUG=False, ficheiros em MEDIA_ROOT não são servidos por defeito.
# True: o Django expõe MEDIA_URL (adequado a ambientes pequenos; em sites muito públicos prefira S3 ou o servidor web).
# No PythonAnywhere pode em vez disso mapear /media/ em Web → Static files (recomendado).
SERVE_MEDIA = config('SERVE_MEDIA', default=False, cast=bool)

# Lista separada por vírgulas no .env, ex.: localhost,127.0.0.1,seuusuario.pythonanywhere.com
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv(),
)

AUTH_USER_MODEL = 'accounts.User'


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # Rate limit / brute-force protection no login (config em baixo)
    'axes',
]

LOCAL_APPS = [
    # Infraestrutura
    'accounts',
    'audit',
    # Entidades base
    'clients',
    'contacts',
    'suppliers',
    # Catalogo e aprovisionamento
    'catalog',
    'procurement',
    # Operacoes
    'services',
    'projects',
    'planning',
    'workforce',
    'timesheets',
    'subcontractors',
    # Comercial
    'budget',
    # Faturação e financeiro
    'invoicing',
    'finance',
    # Frota
    'fleet',
    # Equipamentos e ferramentas
    'equipment',
    # Comercial — Contratos
    'contracts',
    # Modelos de documentos
    'document_templates',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'audit.middleware.CurrentUserMiddleware',

    # django-axes — DEVE ser o último middleware para apanhar logins
    # falhados de qualquer rota (admin, login custom, etc.)
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if config('DATABASE_URL', default=None):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=config('DATABASE_URL'), conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# UI locale: Brazilian Portuguese (msgids in code remain English where gettext is used)
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('pt-br', _('Portuguese (Brazil)')),
    ('en', _('English')),
    ('fr', _('French')),
    ('nl', _('Dutch')),
]

DATE_INPUT_FORMATS = ['%Y-%m-%d']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': config('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# Hardening de produção
# ─────────────────────────────────────────────────────────────────────────────
#
# Tudo abaixo está condicionado a DEBUG=False para não estorvar o ambiente
# local (cookies seguros impedem login em http://127.0.0.1, HSTS prende o
# browser ao https, etc.). Em produção (DEBUG=False) entra automaticamente.
#
# `python manage.py check --deploy` deve ficar limpo neste estado.

# Origins permitidas para POST com CSRF token (ex.: https://construart.eu).
# Lista separada por vírgula no .env. Em produção é OBRIGATÓRIO definir.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=Csv(),
)

if not DEBUG:
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True
    SECURE_SSL_REDIRECT     = True
    # PythonAnywhere termina TLS num proxy à frente — Django só sabe que o
    # request é HTTPS através deste header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # 1h inicialmente. Sobe para 31536000 (1 ano) + preload depois de
    # validares HTTPS estável e quereres entrar nas listas de HSTS preload.
    SECURE_HSTS_SECONDS            = config('SECURE_HSTS_SECONDS', default=3600, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = False
    SECURE_REFERRER_POLICY         = 'same-origin'
    SECURE_CONTENT_TYPE_NOSNIFF    = True
    X_FRAME_OPTIONS                = 'DENY'


# ─────────────────────────────────────────────────────────────────────────────
# django-axes — rate limit de login (anti brute-force)
# ─────────────────────────────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend tem de vir PRIMEIRO para bloquear antes do
    # ModelBackend processar credenciais.
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# 5 tentativas falhadas → bloqueio de 1 hora, combinando username + IP.
AXES_FAILURE_LIMIT       = config('AXES_FAILURE_LIMIT', default=5,  cast=int)
AXES_COOLOFF_TIME        = config('AXES_COOLOFF_TIME',  default=1,  cast=int)  # horas
AXES_RESET_ON_SUCCESS    = True
# Lista de tuplos = AND entre os campos. Bloqueia o par (username, ip)
# em vez de o IP inteiro — evita lockout colateral atrás de NAT.
AXES_LOCKOUT_PARAMETERS  = [['username', 'ip_address']]


# ─────────────────────────────────────────────────────────────────────────────
# Sentry — error tracking (free tier 5k eventos/mês)
# ─────────────────────────────────────────────────────────────────────────────
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Sample baixo: free tier não suporta APM em volume.
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.0, cast=float),
        send_default_pii=False,
        environment=config('SENTRY_ENVIRONMENT', default='production'),
        release=config('SENTRY_RELEASE', default=''),
    )