# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('subcontractors', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PlanningBlankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('line_index', models.PositiveSmallIntegerField()),
                ('text', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('date', 'slot_index', 'line_index'),
                'constraints': [models.UniqueConstraint(fields=('date', 'slot_index', 'line_index'), name='planning_blankline_unique_date_slot_line')],
            },
        ),
        migrations.CreateModel(
            name='PlanningWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('full_day', 'Full Day'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('custom', 'Custom')], default='full_day', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_workers', to='planning.planning')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_plannings', to='subcontractors.subcontractor')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='workforce.collaborator')),
            ],
            options={
                'ordering': ['planning__date', 'worker'],
            },
        ),
        migrations.CreateModel(
            name='PlanningDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_day_offs', to='workforce.collaborator')),
            ],
            options={
                'ordering': ['date', 'worker__name'],
                'constraints': [models.UniqueConstraint(fields=('date', 'worker'), name='planning_dayoff_unique_date_worker')],
            },
        ),
        migrations.CreateModel(
            name='PlanningSubcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_subcontractors', to='planning.planning')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='subcontractors.subcontractor')),
            ],
            options={
                'ordering': ['planning'],
                'unique_together': {('planning', 'subcontractor')},
            },
        ),
    ]
