# Generated by Django 5.2.13 on 2026-04-27 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('planning', '0001_initial'),
        ('workforce', '0005_legalform_migrate_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_assignments', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='planning',
            name='vehicle_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_planning_assignments', to='workforce.collaborator'),
        ),
    ]
