# Generated by Django 5.2.13 on 2026-04-28 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planning_vehicle_planning_vehicle_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ['-date', 'pk']},
        ),
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planning',
            name='is_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='planning.planning'),
        ),
    ]
