# Generated by Django 5.2.13 on 2026-04-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_add_planning_vehicle'),
        ('planning', '0003_add_planning_extension_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='PlanningVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_vehicles', to='planning.planning')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_assignments', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('planning', 'vehicle')},
            },
        ),
    ]
