# Generated by Django 5.2.13 on 2026-04-28 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_planning_vehicle'),
        ('workforce', '0009_add_planning_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningvehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_plannings', to='workforce.collaborator'),
        ),
    ]
