# Generated by Django 5.2.13 on 2026-04-27 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0006_add_driverlicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='License Plate')),
                ('brand', models.CharField(max_length=80, verbose_name='Brand')),
                ('model', models.CharField(max_length=80, verbose_name='Model')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Color')),
                ('vin', models.CharField(blank=True, default='', max_length=50, verbose_name='VIN / Chassis')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], default='diesel', max_length=20, verbose_name='Fuel Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('sold', 'Sold')], default='active', max_length=20, verbose_name='Status')),
                ('current_km', models.PositiveIntegerField(default=0, verbose_name='Current KM')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vehicles', to='workforce.collaborator', verbose_name='Default Driver')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.vehiclecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('insurance', 'Insurance (RC / Omnium)'), ('technical_inspection', 'Technical Inspection (Contrôle Technique)'), ('registration', 'Registration Certificate (DIV)'), ('road_tax', 'Road Tax (Taxe de Circulation)'), ('leasing', 'Leasing / Renting Contract'), ('tachograph', 'Tachograph Calibration'), ('adr', 'ADR Certificate'), ('other', 'Other')], max_length=30, verbose_name='Type')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('insurer_or_entity', models.CharField(blank=True, default='', max_length=120, verbose_name='Insurer / Entity')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference / Policy No.')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Cost (€)')),
                ('file', models.FileField(blank=True, null=True, upload_to='fleet/documents/', verbose_name='File')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'ordering': ['vehicle', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('toll', 'Toll (Viapass / Telepass)'), ('parking', 'Parking'), ('wash', 'Car Wash'), ('tax', 'Tax / Fee'), ('tyre', 'Tyre'), ('other', 'Other')], max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Amount (€)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_expenses', to='workforce.collaborator', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Expense',
                'verbose_name_plural': 'Vehicle Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Offence Date')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Location')),
                ('offence_description', models.TextField(verbose_name='Offence Description')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Amount (€)')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Penalty Points')),
                ('reference', models.CharField(blank=True, default='', max_length=80, verbose_name='Reference / PV No.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('contested', 'Contested')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('deduct_from_payroll', models.BooleanField(default=False, verbose_name='Deduct from Payroll')),
                ('payroll_deducted', models.BooleanField(default=False, verbose_name='Payroll Deducted')),
                ('payroll_deducted_date', models.DateField(blank=True, null=True, verbose_name='Payroll Deduction Date')),
                ('file', models.FileField(blank=True, null=True, upload_to='fleet/fines/', verbose_name='File')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='workforce.collaborator', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('km', models.PositiveIntegerField(verbose_name='KM at Fueling')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Liters')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], default='diesel', max_length=20, verbose_name='Fuel Type')),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Price / Liter (€)')),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Total Cost (€)')),
                ('station', models.CharField(blank=True, default='', max_length=120, verbose_name='Station')),
                ('full_tank', models.BooleanField(default=True, verbose_name='Full Tank')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuelings', to='workforce.collaborator', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelings', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Fueling',
                'verbose_name_plural': 'Fuelings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective')], default='preventive', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done')], default='scheduled', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('km_at_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM at Service')),
                ('next_service_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Next Service KM')),
                ('workshop', models.CharField(blank=True, default='', max_length=150, verbose_name='Workshop / Garage')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Cost (€)')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=80, verbose_name='Invoice Ref.')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
