# Generated by Django 5.2.13 on 2026-04-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_type',
            field=models.CharField(choices=[('insurance', 'Insurance (RC / Omnium)'), ('technical_inspection', 'Technical inspection'), ('registration', 'Registration certificate'), ('road_tax', 'Road tax / circulation tax'), ('leasing', 'Leasing / Renting Contract'), ('tachograph', 'Tachograph Calibration'), ('adr', 'ADR Certificate'), ('other', 'Other')], max_length=30, verbose_name='Type'),
        ),
    ]
