# Generated by Django 5.2.13 on 2026-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_add_planning_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['fleet_number', 'license_plate'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Internal reference number. Must be unique among active vehicles.', null=True, verbose_name='Fleet Number'),
        ),
    ]
