# Generated by Django 5.2.13 on 2026-04-25 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry Date'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exit Date'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='id_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='ID Expiry Date'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workforce/photos/', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='CollaboratorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complement')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Region')),
                ('country', models.CharField(default='Belgium', max_length=100, verbose_name='Country')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='workforce.collaborator')),
            ],
            options={
                'verbose_name': 'Collaborator Address',
                'verbose_name_plural': 'Collaborator Addresses',
                'ordering': ['-valid_from'],
            },
        ),
    ]
