# Generated by Django 5.2.13 on 2026-04-25 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_collaborator_birth_date_collaborator_entry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2'),
        ),
        migrations.CreateModel(
            name='CollaboratorInsuranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=django.utils.timezone.now, verbose_name='Update Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked')),
                ('resolved_at', models.DateField(blank=True, null=True, verbose_name='Resolved At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_notes', to='workforce.collaborator')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_notes_created', to=settings.AUTH_USER_MODEL)),
                ('insurance_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_notes', to='workforce.insurancefund')),
            ],
            options={
                'verbose_name': 'Insurance Note',
                'verbose_name_plural': 'Insurance Notes',
                'ordering': ['-update_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='workforce.language', verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='nationalities',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='workforce.nationality', verbose_name='Nationalities'),
        ),
    ]
