# Generated by Django 5.2.13 on 2026-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_language_nationality_collaborator_email2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20, verbose_name='Abbreviation')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Legal Form',
                'verbose_name_plural': 'Legal Forms',
                'ordering': ['name'],
            },
        ),
    ]
