# Generated by Django 5.2.13 on 2026-04-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_legalform_migrate_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, default='', max_length=50, verbose_name='License Number')),
                ('categories', models.CharField(blank=True, default='', help_text='Comma-separated BE categories, e.g. B,BE,C', max_length=100, verbose_name='Categories')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('issuing_municipality', models.CharField(blank=True, default='', max_length=120, verbose_name='Issuing Municipality')),
                ('scan', models.FileField(blank=True, null=True, upload_to='workforce/licenses/', verbose_name='Scan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license_info', to='workforce.collaborator', verbose_name='Collaborator')),
            ],
            options={
                'verbose_name': 'Driver License',
                'verbose_name_plural': 'Driver Licenses',
            },
        ),
    ]
