# Generated by Django 5.2.13 on 2026-04-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_add_driverlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='collaborator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to='workforce.collaborator', verbose_name='Collaborator'),
        ),
    ]
