# Generated by Django 5.2.13 on 2026-04-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_rename_driverlicense_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlicense',
            name='has_fixed_parking',
            field=models.BooleanField(default=False, verbose_name='Has fixed parking space'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='has_garage',
            field=models.BooleanField(default=False, verbose_name='Has garage at home'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='needs_parking_card',
            field=models.BooleanField(default=False, verbose_name='Needs annual parking card'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='parking_paid_by_company',
            field=models.BooleanField(default=False, verbose_name='Parking paid by company'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='private_use_authorized',
            field=models.BooleanField(default=False, help_text='Is the collaborator authorized to use the vehicle for private purposes?', verbose_name='Private use authorized'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='takes_vehicle_home',
            field=models.BooleanField(default=False, help_text='Does the collaborator take a company vehicle home?', verbose_name='Takes vehicle home'),
        ),
        migrations.CreateModel(
            name='ParkingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name='Registration Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Amount (€)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_permits', to='workforce.driverlicense', verbose_name='Driver License')),
            ],
            options={
                'verbose_name': 'Parking Permit',
                'verbose_name_plural': 'Parking Permits',
                'ordering': ['-registration_date'],
            },
        ),
    ]
