# Generated by Django 5.2.13 on 2026-04-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_add_driverlicense_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratoraddress',
            name='country',
            field=models.CharField(default='Brazil', max_length=100, verbose_name='Country'),
        ),
    ]
