# Generated by Django 5.2.13 on 2026-04-29 17:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0003_alter_budget_options_alter_budgetchapter_options_and_more'),
        ('clients', '0003_alter_clientaddress_options_alter_client_category_and_more'),
        ('projects', '0002_projectinteraction_projectlabourentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Number')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Global discount (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='Default VAT (%)')),
                ('billing_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Billing name')),
                ('billing_address', models.TextField(blank=True, default='', verbose_name='Billing address')),
                ('billing_vat', models.CharField(blank=True, default='', max_length=50, verbose_name='Billing VAT number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('notes_internal', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('notes_client', models.TextField(blank=True, default='', verbose_name='Notes for client')),
                ('payment_terms', models.TextField(blank=True, default='', verbose_name='Payment terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='budget.budget', verbose_name='Budget origin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Unit price (€)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Discount (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT (%)')),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='budget.budgetitem', verbose_name='Budget item origin')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice line',
                'verbose_name_plural': 'Invoice lines',
                'ordering': ['invoice', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-issue_date'], name='invoicing_i_status_40b025_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='invoicing_i_client__488c4d_idx'),
        ),
    ]
