# Generated by Django 5.2.13 on 2026-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='authorization_contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Authorization contact'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='authorization_date',
            field=models.DateField(blank=True, null=True, verbose_name='Authorization date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bon_de_facturation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Authorization number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='execution_notes',
            field=models.TextField(blank=True, default='', verbose_name='Execution notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('direct', 'Direct invoice'), ('advance', 'Advance invoice'), ('from_budget', 'From budget'), ('credit_note', 'Credit note')], default='direct', max_length=20, verbose_name='Invoice type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Work end date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Work start date'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('line', 'Line'), ('title', 'Title (H1)'), ('h2', 'Subtitle H2'), ('h3', 'Subtitle H3'), ('h4', 'Subtitle H4+'), ('comment', 'Comment'), ('page_break', 'Page break')], default='line', max_length=20, verbose_name='Line type'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
    ]
