# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Symbole')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Unite de mesure',
                'verbose_name_plural': 'Unites de mesure',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.productcategory', verbose_name='Categorie parente')),
            ],
            options={
                'verbose_name': 'Categorie de produit',
                'verbose_name_plural': 'Categories de produits',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Marque')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Code-barres')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='Taux TVA (%)')),
                ('sale_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Marge de vente (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Informations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Produit actif')),
                ('is_approved', models.BooleanField(default=False, help_text='Seuls les produits approuves apparaissent dans les devis.', verbose_name='Approuve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='Categorie')),
                ('unit', models.ForeignKey(help_text='Unite interne de reference. Ex: kg, m2, un.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unitofmeasure', verbose_name='Unite de base')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_approved'], name='catalog_pro_is_acti_966f4b_idx'), models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx')],
            },
        ),
    ]
