# Generated by Django 5.2.13 on 2026-04-29 17:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['symbol'], 'verbose_name': 'Unit of measure', 'verbose_name_plural': 'Units of measure'},
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Product active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved products appear in quotes.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Sale margin (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(help_text='Internal reference unit, e.g. kg, m², ea.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unitofmeasure', verbose_name='Base unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=6, verbose_name='VAT rate (%)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.productcategory', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='symbol',
            field=models.CharField(max_length=20, unique=True, verbose_name='Symbol'),
        ),
    ]
