# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('projects', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hours worked')),
                ('hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Rate at the time of entry, frozen for audit.', max_digits=10, null=True, verbose_name='Hourly rate (snapshot)')),
                ('is_overtime', models.BooleanField(default=False, verbose_name='Overtime')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, verbose_name='Overtime multiplier')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning_worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet', to='planning.planningworker', verbose_name='Planning entry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='projects.project', verbose_name='Project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='workforce.collaborator', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'ordering': ['-date', 'worker__name'],
                'indexes': [models.Index(fields=['date', 'project'], name='timesheets__date_56299d_idx'), models.Index(fields=['worker', 'date'], name='timesheets__worker__bf2145_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'project', 'date'), name='unique_timesheet_per_worker_project_day')],
            },
        ),
    ]
