# Generated by Django 5.2.13 on 2026-04-21 20:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Ref. fournisseur')),
                ('supplier_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description fournisseur')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Prix par unite de base du produit.', max_digits=14, verbose_name='Prix unitaire HT')),
                ('package_qty', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Qte par emballage')),
                ('minimum_order_qty', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantite minimale de commande')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Delai de livraison (jours)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Fournisseur prefere')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valide du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_offers', to='catalog.unitofmeasure', verbose_name="Unite d'emballage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offers', to='catalog.product', verbose_name='Produit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_offers', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Offre fournisseur',
                'verbose_name_plural': 'Offres fournisseurs',
                'ordering': ['unit_price'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplierPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Prix HT')),
                ('effective_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifie par')),
                ('product_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='procurement.productsupplier', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Historique de prix',
                'verbose_name_plural': 'Historique des prix',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['product', 'is_active', 'unit_price'], name='procurement_product_454c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['supplier', 'is_active'], name='procurement_supplie_d2cb9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('product', 'supplier')},
        ),
    ]
