# Generated by Cursor (Django 5.2.13) on 2026-04-23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=30, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('partial', 'Parcial'), ('closed', 'Fechado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo para resposta')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Cotação (RFQ)',
                'verbose_name_plural': 'Cotações (RFQ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantidade')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_items', to='catalog.product', verbose_name='Produto')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.rfq', verbose_name='RFQ')),
            ],
            options={
                'verbose_name': 'Item da cotação',
                'verbose_name_plural': 'Itens da cotação',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('answered', 'Respondido'), ('declined', 'Recusado')], default='pending', max_length=20, verbose_name='Estado')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensagem')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='procurement.rfq', verbose_name='RFQ')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_invitations', to='suppliers.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor convidado',
                'verbose_name_plural': 'Fornecedores convidados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Preço unit. HT')),
                ('package_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Qtd por embalagem')),
                ('minimum_order_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Qtd mínima')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (dias)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_lines', to='procurement.rfqitem', verbose_name='Item')),
                ('rfq_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.rfqvendor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Linha de resposta',
                'verbose_name_plural': 'Linhas de resposta',
            },
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'created_at'], name='procurement_rfq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqitem',
            index=models.Index(fields=['rfq', 'product'], name='procurement_rfqitem_rfq_product_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqvendor',
            index=models.Index(fields=['rfq', 'supplier'], name='procurement_rfqvendor_rfq_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqvendor',
            index=models.Index(fields=['status'], name='procurement_rfqvendor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqvendorline',
            index=models.Index(fields=['rfq_vendor', 'rfq_item'], name='procurement_rfqvl_vendor_item_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqitem',
            unique_together={('rfq', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='rfqvendor',
            unique_together={('rfq', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='rfqvendorline',
            unique_together={('rfq_vendor', 'rfq_item')},
        ),
    ]

