# Generated by Cursor (Django 5.2.13) on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_rfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='selected_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_items', to='procurement.rfqvendor', verbose_name='Fornecedor selecionado'),
        ),
    ]

