# Generated by Cursor (Django 5.2.13) on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_rfqitem_selected_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqvendor',
            name='payment_term',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Prazo de pagamento'),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='quote_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do orçamento'),
        ),
    ]
