# Generated by Cursor (Django 5.2.13) on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rfqvendor_commercial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqvendor',
            name='quote_contact_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Contacto comercial a tratar desta cotação junto do fornecedor.',
                max_length=255,
                verbose_name='Responsável pelo orçamento',
            ),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='quote_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefone (orçamento)'),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='quote_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail (orçamento)'),
        ),
    ]
