# Generated by Cursor (Django 5.2.13) on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('procurement', '0005_rfqvendor_quote_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqvendor',
            name='quote_contact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rfq_vendors',
                to='suppliers.suppliercontact',
                verbose_name='Responsável (contacto)',
            ),
        ),
    ]
