# Generated by Django 5.2.13 on 2026-05-08 18:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_productcategory_options_and_more'),
        ('procurement', '0006_rfqvendor_quote_contact_fk'),
        ('suppliers', '0004_supplier_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsupplier',
            options={'ordering': ['unit_price'], 'verbose_name': 'Supplier offer', 'verbose_name_plural': 'Supplier offers'},
        ),
        migrations.AlterModelOptions(
            name='productsupplierpricehistory',
            options={'ordering': ['-effective_date'], 'verbose_name': 'Price history entry', 'verbose_name_plural': 'Price history'},
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request for quotation (RFQ)', 'verbose_name_plural': 'Requests for quotation (RFQ)'},
        ),
        migrations.AlterModelOptions(
            name='rfqitem',
            options={'ordering': ['id'], 'verbose_name': 'RFQ line', 'verbose_name_plural': 'RFQ lines'},
        ),
        migrations.AlterModelOptions(
            name='rfqvendor',
            options={'ordering': ['id'], 'verbose_name': 'Invited supplier', 'verbose_name_plural': 'Invited suppliers'},
        ),
        migrations.AlterModelOptions(
            name='rfqvendorline',
            options={'verbose_name': 'Response line', 'verbose_name_plural': 'Response lines'},
        ),
        migrations.RenameIndex(
            model_name='rfq',
            new_name='procurement_status_e6707d_idx',
            old_name='procurement_rfq_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='rfqitem',
            new_name='procurement_rfq_id_9a0404_idx',
            old_name='procurement_rfqitem_rfq_product_idx',
        ),
        migrations.RenameIndex(
            model_name='rfqvendor',
            new_name='procurement_rfq_id_f1f4d5_idx',
            old_name='procurement_rfqvendor_rfq_supplier_idx',
        ),
        migrations.RenameIndex(
            model_name='rfqvendor',
            new_name='procurement_status_c4bdc4_idx',
            old_name='procurement_rfqvendor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='rfqvendorline',
            new_name='procurement_rfq_ven_125f89_idx',
            old_name='procurement_rfqvl_vendor_item_idx',
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='Preferred supplier'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Lead time (days)'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='minimum_order_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Minimum order quantity'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='package_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantity per package'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='package_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_offers', to='catalog.unitofmeasure', verbose_name='Package unit'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offers', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_offers', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Supplier description'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Supplier reference'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Price per base unit of the product.', max_digits=14, verbose_name='Unit price excl. VAT'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='productsupplierpricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='productsupplierpricehistory',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='productsupplierpricehistory',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Price excl. VAT'),
        ),
        migrations.AlterField(
            model_name='productsupplierpricehistory',
            name='product_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='procurement.productsupplier', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Response due date'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='number',
            field=models.CharField(blank=True, default='', max_length=30, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partial'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_items', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='selected_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_items', to='procurement.rfqvendor', verbose_name='Selected vendor'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='payment_term',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Payment term'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='quote_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_vendors', to='suppliers.suppliercontact', verbose_name='Quote contact'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='quote_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Quote contact email'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='quote_contact_name',
            field=models.CharField(blank=True, default='', help_text='Commercial contact at the supplier for this RFQ.', max_length=255, verbose_name='Quote contact name'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='quote_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Quote contact phone'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='quote_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Quote valid until'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('answered', 'Answered'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rfqvendor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_invitations', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Answered at'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (days)'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='minimum_order_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Minimum order quantity'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='package_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Quantity per package'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='rfq_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.rfqvendor', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Unit price excl. VAT'),
        ),
        migrations.AlterField(
            model_name='rfqvendorline',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid until'),
        ),
    ]
